# Generated by Django 3.0.6 on 2020-06-05 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_course_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_head', models.CharField(default='', max_length=30)),
                ('dept_name', models.CharField(choices=[('Literature', 'Lit'), ('Mathematics', 'Mat'), ('Economics', 'Eco'), ('Philosophy', 'Phi'), ('Psychology', 'Psy'), ('Biology', 'Bio'), ('Politics', 'Pol'), ('History', 'His'), ('Computer Science', 'Cs'), ('Finance', 'Fin'), ('International Relations', 'Ir'), ('Foundation Course', 'Fc')], default='Foundation Course', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='professor',
            name='prof_dep',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Department'),
        ),
    ]
