# Generated by Django 3.0.6 on 2020-06-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200605_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='prof_dep',
            field=models.CharField(default='', max_length=30),
        ),
    ]
