# Generated by Django 3.0.6 on 2020-06-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200605_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
