# Generated by Django 2.2.6 on 2020-06-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='prof_pic',
            field=models.CharField(default=' ', max_length=70),
        ),
    ]
