# Generated by Django 2.2.6 on 2020-06-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_professor_prof_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='prof_courses',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='professor',
            name='prof_pic',
            field=models.CharField(default='', max_length=50),
        ),
    ]
