# Generated by Django 2.2.6 on 2020-06-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200610_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='prof_pic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
