# Generated by Django 3.0.7 on 2020-06-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200610_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='take_again',
            field=models.BooleanField(default=False),
        ),
    ]
