# Generated by Django 3.0.7 on 2020-06-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20200611_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='helpful',
            field=models.IntegerField(default=0),
        ),
    ]
