# Generated by Django 2.2.6 on 2020-06-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rating_num_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='num_5',
        ),
        migrations.AddField(
            model_name='course',
            name='num_5',
            field=models.IntegerField(default=0),
        ),
    ]
