# Generated by Django 2.2.6 on 2020-06-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20200611_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='num_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='num_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='num_4',
            field=models.IntegerField(default=0),
        ),
    ]
