# Generated by Django 2.2.6 on 2020-06-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20200611_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='per_5',
            field=models.IntegerField(default=0),
        ),
    ]
