# Generated by Django 2.2.6 on 2020-06-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_course_per_5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='num_5',
            new_name='num_five',
        ),
    ]
