# Generated by Django 2.2.6 on 2020-06-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20200611_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='num_five',
            new_name='num',
        ),
    ]
