# Generated by Django 2.2.6 on 2020-06-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20200611_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='per_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='per_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='per_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='per_4',
            field=models.IntegerField(default=0),
        ),
    ]
