# Generated by Django 2.2.6 on 2020-06-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20200611_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='AM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='BM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='BP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='C',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='CM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='CP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='F',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='gp_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='grade_offered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='grade_point',
            field=models.FloatField(default=0),
        ),
    ]
