# Generated by Django 2.2.6 on 2020-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20200611_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_number_of_ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_rating',
            field=models.FloatField(default=3.0),
        ),
    ]
