# Generated by Django 2.2.6 on 2020-06-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20200611_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='num_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='num_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='num_3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='num_4',
        ),
        migrations.RemoveField(
            model_name='course',
            name='num_5',
        ),
        migrations.RemoveField(
            model_name='course',
            name='per_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='per_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='per_3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='per_4',
        ),
        migrations.RemoveField(
            model_name='course',
            name='per_5',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number_of_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
    ]
