# Generated by Django 2.2.6 on 2020-06-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20200612_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='A',
        ),
        migrations.RemoveField(
            model_name='course',
            name='AM',
        ),
        migrations.RemoveField(
            model_name='course',
            name='B',
        ),
        migrations.RemoveField(
            model_name='course',
            name='BM',
        ),
        migrations.RemoveField(
            model_name='course',
            name='BP',
        ),
        migrations.RemoveField(
            model_name='course',
            name='C',
        ),
        migrations.RemoveField(
            model_name='course',
            name='CM',
        ),
        migrations.RemoveField(
            model_name='course',
            name='CP',
        ),
        migrations.RemoveField(
            model_name='course',
            name='F',
        ),
    ]
