# Generated by Django 2.2.6 on 2020-06-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20200612_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_number_of_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
    ]
