# Generated by Django 2.2.6 on 2020-06-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20200613_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='prof_dep',
            field=models.CharField(choices=[('ENG', 'English'), ('POL', 'Political Science'), ('MAT', 'Mathematics'), ('ECO', 'Economocis'), ('HIS', 'History'), ('SOA', 'Sociology and Anthropology'), ('PSY', 'Psychology'), ('PHI', 'Philosophy'), ('BIO', 'Biology'), ('PHY', 'Physics'), ('CHM', 'Chemistry'), ('FIN', 'Finance'), ('CS', 'Computer Science'), ('CC', 'Co-Curricular'), ('FC', 'Foundation Course'), ('CW', 'Creative Writing'), ('ES', 'Environmental Studies'), ('ENT', 'Entrepreneurship'), ('MS', 'Media Studies'), ('IR', 'International Relations'), ('PA', 'Performing Arts'), ('VA', 'Visual Arts')], default='', max_length=30),
        ),
    ]
