# Generated by Django 2.2.6 on 2020-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_auto_20200613_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='retakes',
            field=models.IntegerField(default=0),
        ),
    ]
