# Generated by Django 2.2.6 on 2020-06-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_course_retakes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='retakes',
        ),
    ]
