# Generated by Django 2.2.6 on 2020-06-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_remove_course_retakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_retakers',
            field=models.IntegerField(default=0),
        ),
    ]
