# Generated by Django 3.0.7 on 2020-06-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_course_course_retakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='prof_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
