# Generated by Django 2.2.6 on 2020-06-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_auto_20200624_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
