# Generated by Django 3.0.7 on 2020-06-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
