# Generated by Django 3.0.7 on 2020-06-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_rating_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_cross',
            field=models.CharField(choices=[('ENG', 'English'), ('POL', 'Political Science'), ('MAT', 'Mathematics'), ('ECO', 'Economocis'), ('HIS', 'History'), ('SOA', 'Sociology and Anthropology'), ('PSY', 'Psychology'), ('PHI', 'Philosophy'), ('BIO', 'Biology'), ('PHY', 'Physics'), ('CHM', 'Chemistry'), ('FIN', 'Finance'), ('CS', 'Computer Science'), ('CC', 'Co-Curricular'), ('FC', 'Foundation Course'), ('CW', 'Creative Writing'), ('ES', 'Environmental Studies'), ('ENT', 'Entrepreneurship'), ('MS', 'Media Studies'), ('IR', 'International Relations'), ('PA', 'Performing Arts'), ('VA', 'Visual Arts')], default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_listing',
            field=models.CharField(choices=[('ENG', 'English'), ('POL', 'Political Science'), ('MAT', 'Mathematics'), ('ECO', 'Economocis'), ('HIS', 'History'), ('SOA', 'Sociology and Anthropology'), ('PSY', 'Psychology'), ('PHI', 'Philosophy'), ('BIO', 'Biology'), ('PHY', 'Physics'), ('CHM', 'Chemistry'), ('FIN', 'Finance'), ('CS', 'Computer Science'), ('CC', 'Co-Curricular'), ('FC', 'Foundation Course'), ('CW', 'Creative Writing'), ('ES', 'Environmental Studies'), ('ENT', 'Entrepreneurship'), ('MS', 'Media Studies'), ('IR', 'International Relations'), ('PA', 'Performing Arts'), ('VA', 'Visual Arts')], default='', max_length=30),
        ),
    ]
