# Generated by Django 3.0.7 on 2020-07-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_auto_20200713_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='', max_length=80),
        ),
    ]
